### PR TITLE
Add tables and queries

### PR DESCRIPTION
**Pull request by ClintonYounge**
### UPDATES
- Created a many to many joining table (vets), specializations and visits table with updated values
- Add join queries

**Below are the first 5 prompts**
first 5 queries

**Below are the last 4 prompts**
last 4 queries

### CODE REVIEW

**Review by TadesseDev — CHANGES_REQUESTED** [review]
### Hi @ClintonYounge 

### I'm Tadesse Alemayehu your reviewer for this PR. :hand: 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
212094426-b41dd457-c9db-4ab3-bbe9-176dd8dd08b7




## Highlights
 - [x] Good way of organizing your queries with a comment on a head ✅
 - [x] You have written a clean code ✅
 
## Required Changes ♻️
- [ ] Dear @ClintonYounge, I notice you have not made a change to your `data.sql` file, where we are expected to insert our data, Please write the commands for inserting the required data. 
image
**If you have forgotten to push the changes, Please do. We need to  see all the changes**

_Check the comments under the review._

## Optional suggestions
- [Optional] Commit messages are usually expected to be atomic, where we commit every related commits in one, This makes it easy to debug our code later on. I notice you commit `[Add tables and queries](https://github.com/ClintonYounge/Vet-Clinic-DB/pull/4/commits/899d91d75ed12db269fb36c2870c8aa8e8a5976c)`, I would suggest making this two commit and use `Add tables and `Add queries`. this makes it easy to follow up on your code history.


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ClintonYounge** [comment]
@TadesseDev Thanks a lot. Finished last min and didn't notice. Was having lots of problems and finally got everything sorted.

**Comment by ClintonYounge** [comment]
@TadesseDev I accidentally requested ur review. Sorry.

**Review by TadesseDev — APPROVED** [review]
### Hi @ClintonYounge 

### I'm Tadesse Alemayehu your reviewer for this PR. :hand: 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
giphy (1)



## Highlights
 - [x] Good job making the changes requested earlier. ✅


## Optional suggestions

- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
